### ISSUE TITLE
[ui] allow prod and env builds + fix packages.json

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#113]
This is the same as you wrote:

Put a .env file on the server where the frontend runs (prod api base url...)

Thanks!

**Comment by LordNoteworthy** [comment]
Shall we do something here ? What do you think ?

I have seen a warning that an .env files does not exist when I do yarn build ? 

Maybe you can also take a look at the performance of the minification and webpack, if there is anything we can improve, let me know.

**Comment by LordNoteworthy** [comment]
@mrassili reference this issue when you fix the issues we talked about.

**Comment by LordNoteworthy** [comment]
I think we can close this one, right?

**Comment by mrassili** [comment]
Yes
