### ISSUE TITLE
[ui] Request password reset

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#117]
Let's start by designing a password reset page.

Should be similar to the login one but will contain only one field which is the email which to request a password for. Do validation in the client-side for the email.

Then send me that email to: `api.saferwall.com/auth/password/reset/`

If you get status code 200: You could then warn the user with a message like:
The first step of the password reset process has been successfully completed, in a few minutes you will receive an email with further instructions to create a new password.

if you get status code 404:: Which is the email is not found in DB just warn the user that that email he requests to change the password for does not exist in our DB.

**Comment by mrassili** [comment]
Working on it 😉

**Comment by mrassili** [comment]
Done
