### ISSUE TITLE
[ui] Fix few routing problems

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#131]
Hi @mrassili 

First issue:

When you are talking to the backend:
```
axios
      .get(`/api/v1/files/${this.$route.params.hash}/`)
 ```

When you do that, it tries to use the host name of the UI, though the backend and the frontend are not in the same server. In production, the UI will be hosted directly on `saferwall.com`, and the backend is on `api.saferwall.com`. So You need to expose an entry in the config for the backend.

Second issue:

When you click in antivirus for example, at the moment, it takes you to a particular hardcoded url, normally, it should be displaying the context of the file we are looking at it now, by that I mean if the user searched a file using the top search bar, the context is that hash, so imagine someone wrote: 

```275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f```

When the user clicks on antivirus, the ui url should be:
```http://saferwall.com/files/df50dd428c2c0a6c2bffc6720b10d690061f1e3e0d1f5ef2f926942cbf4fc69c/antivirus```

Same applies for all components in the left side bar.

Cheers.

**Comment by LordNoteworthy** [comment]
This issue has a priority over the other one.

**Comment by mrassili** [comment]
on it

**Comment by mrassili** [comment]
@LordNoteworthy the production api base url should be set on a `.env` file directly in the production server and Webpack should be able to pick it up
In dev, we already have it set up `dev.api.saferwall.com`
Is that what you meant?

**Comment by mrassili** [comment]
Also, the schema for `v1/files` has changed, we had `first_scan` and `last_scan` under `multiav`, can you confirm?

**Comment by LordNoteworthy** [comment]
Hey @mrassili 

For first_scan and last_scan. they are back, I just forgot them.

**Comment by LordNoteworthy** [comment]
Once I added the .env file, everything worked file. Though when I build it inside the container and run it from nginx, seems like he does not take into account the env variables, maybe you can give it a try and check it.

**Comment by mrassili** [comment]
> Once I added the .env file, everything worked file. Though when I build it inside the container and run it from nginx, seems like he does not take into account the env variables, maybe you can give it a try and check it.

@LordNoteworthy You are right, we should refactor to create a global `axios` that picks the right `baseUrl` (dynamically) as @Akhouad suggested, he might be interested in making the changes, if not I can do it

**Comment by LordNoteworthy** [comment]
@Akhouad seems to did it in the open PR, I just need to merge it, there are some conflicts and you have added a package-lock which conflicts with his one.

**Comment by LordNoteworthy** [comment]
Thanks @mrassili 

@Akhouad I merged your code as well, and deployed it. Now, if you go to dev.saferwall.com and naviguate arround, you will see that still it tries to contact the client URL, this behavior happen does not happen when I run it using the dev server with node, but if you build it and you use nginx to serve the builded html, it does not work. This need to be fixed. Whoever have time can pick any issue and work on it.
