### ISSUE TITLE
[ui] general improvement of UI

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#132]
Hi @mrassili 

This issue is about many small improvements we need to do before we release the v0.0.1.

1. Some features are not yet fully finished from my side. Let's hide them from the UI for now.
- At the top navbar, `statistics` and `search` needs to be hidden, you can just comment code so it does not show up.
- There is an upload button with icon in the top navbar in the middle, let's take that one out as well.
- Keep the `upload` which is on the top-right side of the navbar, add to it an `ulpload` icon.
2. At the left sidebar, let's hide `Dynamic analysis` and its descendants.
3. At the top left corner, there is an image `saferwall`, let's change it with the one we have in the root project README.

Cheers.

**Comment by Akhouad** [comment]
@LordNoteworthy 
I've made the changes... please see branch ui/132
regarding the upload button at top center, it's the submit button for the search input in header... would you liike to remove that search input as well?

**Comment by Akhouad** [comment]
And btw i had to increase header's height in order to show the new logo correctly.

**Comment by LordNoteworthy** [comment]
I checked the branch ui/fix_2. 2 gotchas:

1. When you click on upload, it should take you to `/upload/` now it seems nothing happens.
2. The logo still appears pretty big, I would say reduce its size by 50%, and the text `saferwall` next to the logo could be increased by 20%.

**Comment by LordNoteworthy** [comment]
@Akhouad when you have time, check this first.
