### ISSUE TITLE
Stuck at building Consumer

### ISSUE THREAD

**Issue by hotail** [saferwall/saferwall#217]
Hello Team.

I have these Error:
Installing Capstone...
make[1]: Entering directory '/saferwall/capstone/cstool'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/saferwall/capstone/cstool'
make -C tests
make[1]: Entering directory '/saferwall/capstone/tests'
/bin/sh: cc: not found
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/saferwall/capstone/tests'
make -C suite/fuzz
make[1]: Entering directory '/saferwall/capstone/suite/fuzz'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/saferwall/capstone/suite/fuzz'

Step 8/35 : RUN GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags '-extldflags "-static"'     -o /go/bin/consumer pkg/consumer/main.go pkg/consumer/helpers.go pkg/consumer/scanners.go pkg/consumer/tagger.go
 ---> Running in 0389a35b4612
# runtime/cgo
exec: "gcc": executable file not found in $PATH
The command '/bin/sh -c GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags '-extldflags "-static"'     -o /go/bin/consumer pkg/consumer/main.go pkg/consumer/helpers.go pkg/consumer/scanners.go pkg/consumer/tagger.go' returned a non-zero code: 2
make: *** [build/mk/docker.mk:4: docker-build] Error 2
make: *** [build/mk/consumer.mk:2: consumer-build] Error 2

i tried to install saferwall in local host

**Comment by LordNoteworthy** [comment]
@hotail 

Does it happen when you tried to run `make  consumer-build` ?

Cheers.

**Comment by hotail** [comment]
> @hotail
> 
> Does it happen when you tried to run `make consumer-build` ?
> 
> Cheers.

Yes, i have tried to add apk build-base and gcc but error still happen

**Comment by LordNoteworthy** [comment]
Pretty weird  :)

I just pulled the image and did:
1. sudo docker run -it golang:1.14-alpine /bin/sh
2. Run the first command in the docker file:
```
apk update && apk add --no-cache git ca-certificates tzdata alpine-sdk \
>     && update-ca-certificates
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.0-175-g8b3334c57c [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.0-173-g65101f0f4e [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12749 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/37) Installing fakeroot (1.24-r0)
(2/37) Installing openssl (1.1.1g-r0)
(3/37) Installing libattr (2.4.48-r0)
(4/37) Installing attr (2.4.48-r0)
(5/37) Installing libacl (2.2.53-r0)
(6/37) Installing tar (1.32-r1)
(7/37) Installing pkgconf (1.7.2-r0)
(8/37) Installing patch (2.7.6-r6)
(9/37) Installing libgcc (9.3.0-r2)
(10/37) Installing libstdc++ (9.3.0-r2)
(11/37) Installing lzip (1.21-r0)
(12/37) Installing nghttp2-libs (1.41.0-r0)
(13/37) Installing libcurl (7.69.1-r0)
(14/37) Installing curl (7.69.1-r0)
(15/37) Installing abuild (3.6.0-r0)
Executing abuild-3.6.0-r0.pre-install
(16/37) Installing binutils (2.34-r1)
(17/37) Installing libmagic (5.38-r0)
(18/37) Installing file (5.38-r0)
(19/37) Installing gmp (6.2.0-r0)
(20/37) Installing isl (0.18-r0)
(21/37) Installing libgomp (9.3.0-r2)
(22/37) Installing libatomic (9.3.0-r2)
(23/37) Installing libgphobos (9.3.0-r2)
(24/37) Installing mpfr4 (4.0.2-r4)
(25/37) Installing mpc1 (1.1.0-r1)
(26/37) Installing gcc (9.3.0-r2)
(27/37) Installing musl-dev (1.1.24-r9)
(28/37) Installing libc-dev (0.7.2-r3)
(29/37) Installing g++ (9.3.0-r2)
(30/37) Installing make (4.3-r0)
(31/37) Installing fortify-headers (1.1-r0)
(32/37) Installing build-base (0.5-r2)
(33/37) Installing expat (2.2.9-r1)
(34/37) Installing pcre2 (10.35-r0)
(35/37) Installing git (2.26.2-r0)
(36/37) Installing alpine-sdk (1.0-r0)
(37/37) Installing tzdata (2020a-r0)
Executing busybox-1.31.1-r16.trigger
OK: 228 MiB in 52 packages
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```

3. Run gcc:
```
/go # gcc --version
gcc (Alpine 9.3.0) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Can you paste the output from the make consumer-build please.

**Comment by hotail** [comment]
Dear LordNoteworthy.

+Action 1:
No error while i use 
# supported values ['virtualbox', 'kvm2', 'none']
export MINIKUBE_DRIVER=virtualbox

but i dont understand how to use "Before running any of the builds below, if you are not using the none driver, make sure to eval the minikube environment variables into your shell using the command: eval $(minikube docker-env)." 

+So  i did Action 2:
# supported values ['virtualbox', 'kvm2', 'none']
export MINIKUBE_DRIVER=none

-----
**kmaster@kmaster:~/saferwall$ make minikube-start**
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /root
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
# sudo mv /root/.kube /home/kmaster/.kube # this will write over any previous configuration
sudo chown -R kmaster /home/kmaster/.kube
chown: cannot access '/home/kmaster/.kube': No such file or directory
make: *** [build/mk/minikube.mk:15: minikube-start] Error 1
-------
**kmaster@kmaster:~/saferwall$ kubectl version**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
**kmaster@kmaster:~/saferwall$ kubectl version --client**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

--------
**kmaster@kmaster:~/saferwall$ make consumer-build**
sudo make docker-build IMG=consumer DOCKER_FILE=build/docker/Dockerfile.consumer DOCKER_DIR=.
docker build  -t saferwall/consumer -f build/docker/Dockerfile.consumer .
Sending build context to Docker daemon  74.63MB
Step 1/34 : FROM golang:1.14-alpine AS builder
1.14-alpine: Pulling from library/golang
df20fa9351a1: Pull complete 
ed8968b2872e: Pull complete 
a92cc7c5fd73: Pull complete 
00abe362642d: Pull complete 
e0491c15e88f: Pull complete 
Digest: sha256:d6deb50437547fd7226890aa19b075fbf7f5063e3c0d7a2eaf7fb41d11069013
Status: Downloaded newer image for golang:1.14-alpine
 ---> 30df784d6206
Step 2/34 : RUN apk update && apk add --no-cache git ca-certificates tzdata alpine-sdk     && update-ca-certificates 2>/dev/null || true
 ---> Running in 16d75de64141
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.0-175-g8b3334c57c [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.0-173-g65101f0f4e [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12749 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/37) Installing fakeroot (1.24-r0)
(2/37) Installing openssl (1.1.1g-r0)
(3/37) Installing libattr (2.4.48-r0)
(4/37) Installing attr (2.4.48-r0)
(5/37) Installing libacl (2.2.53-r0)
(6/37) Installing tar (1.32-r1)
(7/37) Installing pkgconf (1.7.2-r0)
(8/37) Installing patch (2.7.6-r6)
(9/37) Installing libgcc (9.3.0-r2)
(10/37) Installing libstdc++ (9.3.0-r2)
(11/37) Installing lzip (1.21-r0)
(12/37) Installing nghttp2-libs (1.41.0-r0)
(13/37) Installing libcurl (7.69.1-r0)
(14/37) Installing curl (7.69.1-r0)
(15/37) Installing abuild (3.6.0-r0)
Executing abuild-3.6.0-r0.pre-install
(16/37) Installing binutils (2.34-r1)
(17/37) Installing libmagic (5.38-r0)
(18/37) Installing file (5.38-r0)
(19/37) Installing gmp (6.2.0-r0)
(20/37) Installing isl (0.18-r0)
(21/37) Installing libgomp (9.3.0-r2)
(22/37) Installing libatomic (9.3.0-r2)
(23/37) Installing libgphobos (9.3.0-r2)
(24/37) Installing mpfr4 (4.0.2-r4)
(25/37) Installing mpc1 (1.1.0-r1)
(26/37) Installing gcc (9.3.0-r2)
**ERROR: gcc-9.3.0-r2: Permission denied**
(27/37) Installing musl-dev (1.1.24-r9)
(28/37) Installing libc-dev (0.7.2-r3)
(29/37) Installing g++ (9.3.0-r2)
(30/37) Installing make (4.3-r0)
(31/37) Installing fortify-headers (1.1-r0)
(32/37) Installing build-base (0.5-r2)
(33/37) Installing expat (2.2.9-r1)
(34/37) Installing pcre2 (10.35-r0)
(35/37) Installing git (2.26.2-r0)
(36/37) Installing alpine-sdk (1.0-r0)
(37/37) Installing tzdata (2020a-r0)
Executing busybox-1.31.1-r16.trigger
1 error; 124 MiB in 51 packages
Removing intermediate container 16d75de64141
 ---> 4ed2b661fefa
Step 3/34 : WORKDIR /saferwall
 ---> Running in 5b65f514a5e9
Removing intermediate container 5b65f514a5e9
 ---> b13443e4fd7c
Step 4/34 : COPY . .
 ---> 2be9b3a343e6
Step 5/34 : RUN go mod download
 ---> Running in 049002ec98fd
Removing intermediate container 049002ec98fd
 ---> bb896e081485
Step 6/34 : RUN echo "Installing Capstone..."     && git clone https://github.com/aquynh/capstone.git     && cd capstone     && ./make.sh     && ./make.sh install
 ---> Running in b49db39b0f4e
Installing Capstone...
Cloning into 'capstone'...
  CC      cs.o
  CC      utils.o
make: cc: No such file or directory
make: *** [Makefile:507: cs.o] Error 127
make: *** Waiting for unfinished jobs....
make: cc: No such file or directory
make: *** [Makefile:507: utils.o] Error 127
The command '/bin/sh -c echo "Installing Capstone..."     && git clone https://github.com/aquynh/capstone.git     && cd capstone     && ./make.sh     && ./make.sh install' returned a non-zero code: 2
make: *** [build/mk/docker.mk:4: docker-build] Error 2
make: *** [build/mk/consumer.mk:2: consumer-build] Error 2

**Comment by LordNoteworthy** [comment]
I see, some root privileges issue, what linux host ur using ? and what version ?

**Comment by hotail** [comment]
> I see, some root privileges issue, what linux host ur using ? and what version ?

I am using Debian 10

**Comment by LordNoteworthy** [comment]
Debian does have `sudo` installed by default. You can do something like this (from StackOverflow):

![image](https://user-images.githubusercontent.com/5129564/88112153-9d4fd380-cbf2-11ea-8dc2-1c46374b4c3b.png)

**Comment by hotail** [comment]
> 
> 
> Debian does not have `sudo` installed by default. You can do something like this (from StackOverflow):
> 
> ![image](https://user-images.githubusercontent.com/5129564/88112153-9d4fd380-cbf2-11ea-8dc2-1c46374b4c3b.png)

Thank you. I found out that it has been block by proxy.
