### ISSUE TITLE
Error while make multiav-build-go

### ISSUE THREAD

**Issue by hotail** [saferwall/saferwall#221]
Dear Saferwall Team.

**i got stuck at making multiav-build-go**

[*] =============== Building go-clamav ===============
make[1]: Entering directory '/home/saferwall/saferwall'
sudo make docker-build IMG=goclamav VERSION=0.0.2 \
 DOCKER_FILE=build/docker/Dockerfile.goclamav \
 DOCKER_DIR=pkg/grpc/multiav/clamav/server
docker build  -t saferwall/goclamav -f build/docker/Dockerfile.goclamav pkg/grpc/multiav/clamav/server
Sending build context to Docker daemon  5.167kB
Step 1/17 : FROM golang:1.14-alpine AS builder
 ---> 30df784d6206
Step 2/17 : RUN apk update && apk add --no-cache git ca-certificates tzdata     && update-ca-certificates 2>/dev/null || true
 ---> Using cache
 ---> 4363dbd6c935
Step 3/17 : WORKDIR $GOPATH/src/saferwall/clamav/
 ---> Using cache
 ---> 5ef4c90682cd
Step 4/17 : COPY . .
 ---> Using cache
 ---> aa8bec7444e9
Step 5/17 : RUN go get -d -v
 ---> Running in 234abb799a92
github.com/minio/minio-go (download)
package github.com/minio/minio-go/v6: cannot find package "github.com/minio/minio-go/v6" in any of:
        /usr/local/go/src/github.com/minio/minio-go/v6 (from $GOROOT)
        /go/src/github.com/minio/minio-go/v6 (from $GOPATH)

The command '/bin/sh -c go get -d -v' returned a non-zero code: 1
build/mk/docker.mk:4: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1
build/mk/multiav.mk:59: recipe for target 'multiav-build-av-go' failed
make[1]: *** [multiav-build-av-go] Error 2
make[1]: Leaving directory '/home/saferwall/saferwall'
/bin/bash: line 4: test: !: binary operator expected

**Comment by LordNoteworthy** [comment]
Hi @hotail 

Looking into it.

Cheers.

**Comment by LordNoteworthy** [comment]
Hello @hotail 

Sorry for my late answer.

I updated the code, you don't need anymore to build the containers.

Have a look at the documentation, it includes a few steps and before you start re-doing the cluster, you need to delete the helm cluster before.

Cheers.

**Comment by hotail** [comment]
Dear @LordNoteworthy 

Thank you for your information. 
I am very new in docker world. So i rewrote multi-AV in python and use simple container to run it. 

Cheers

**Comment by LordNoteworthy** [comment]
No worries @hotail 

Can I close this one? Or you still need some help?
