### ISSUE TITLE
Any plans to include more AV?

### ISSUE THREAD

**Issue by nikAizuddin** [saferwall/saferwall#228]
Hi, is there any plan to include more AV such as from [Malice-Plugins](https://github.com/malice-plugins)?

**Comment by LordNoteworthy** [comment]
Hello,

I would be happy to do so, anyone or 2 you would like to have first? 

If you have a list of preferences, I would start with them.

Cheers.

**Comment by nikAizuddin** [comment]
@LordNoteworthy Thank you! If possible, here the following AV that I would like to request:
1. [AVG](https://github.com/malice-plugins/avg)
1. [DrWeb](https://github.com/malice-plugins/drweb)
1. [FProt](https://github.com/malice-plugins/fprot)
1. [EScan](https://github.com/malice-plugins/escan)

**Comment by LordNoteworthy** [comment]
Roger that, I will try to get them by end of the week.

**Comment by LordNoteworthy** [comment]
Hey @nikAizuddin 

DrWeb is done.

![image](https://user-images.githubusercontent.com/5129564/90132239-cb1ed700-ddb0-11ea-9c40-7aaba4ab80c9.png)

Moving to AVG.

**Comment by nikAizuddin** [comment]
@LordNoteworthy awesome

**Comment by LordNoteworthy** [comment]
I added TrendMicro today.

**Comment by nikAizuddin** [comment]
@LordNoteworthy Thank you
