### ISSUE TITLE
Potential import collision: import path "github.com/bitly/go-nsq" should be deleted

### ISSUE THREAD

**Issue by KateGo520** [saferwall/saferwall#232]
## Background
I find that `github.com/nsqio/go-nsq` and `github.com/bitly/go-nsq` coexist in this repo：
https://github.com/saferwall/saferwall/blob/master/go.mod#L7 （Line 7 & 16）
```
github.com/bitly/go-nsq v1.0.7
github.com/nsqio/go-nsq v1.0.8
```
The "github.com/nsqio/go-nsq" and "github.com/bitly/go-nsq" are the same repos. The "github.com/bitly/go-nsq" has already been redirected to "github.com/nsqio/go-nsq". "github.com/bitly/go-nsq" is the old path of `go-nsq`.
https://github.com/nsqio/go-nsq/blob/v1.0.7/config_flag_test.go
```
package nsq_test
import (
	"flag"
	"github.com/nsqio/go-nsq"
)
```
And it seems to be nowhere to use the import path "github.com/bitly/go-nsq" in this repo.
https://github.com/saferwall/saferwall/search?q=bitly%2Fgo-nsq&unscoped_q=bitly%2Fgo-nsq

```
$go mod why github.com/bitly/go-nsq
# github.com/bitly/go-nsq
(main module does not need package github.com/bitly/go-nsq)
```

## Solution
Delete the old import paths `"github.com/bitly/go-nsq"`.
Where did you import it: https://github.com/saferwall/saferwall/search?q=bitly%2Fgo-nsq&unscoped_q=bitly%2Fgo-nsq

**Comment by KateGo520** [comment]
@LordNoteworthy  @Kerkesni  Could you help me review this issue? Thx :p

**Comment by LordNoteworthy** [comment]
Hey @KateGo520, thanks for the catch.

https://github.com/saferwall/saferwall/commit/20070442b5d7730ca0d777474c4f05682f90bbad should fix it. 

Does it look ok now ?

**Comment by KateGo520** [comment]
@LordNoteworthy  Thank you for your contribution! It looks good to me.
