### ISSUE TITLE
Error Make ui-build

### ISSUE THREAD

**Issue by hotail** [saferwall/saferwall#234]
Dear Team,

frontend.mk require Dockerfile.frontend and it is missing in saferwall/build/docker/
previous version Docker file to build UI was Dockerfile and it was in saferwall/ui/

Cheers

**Comment by LordNoteworthy** [comment]
Oh my, forgot pushing that.

Just pushed it.

Cheers.

**Comment by hotail** [comment]
Thank you @LordNoteworthy
