### ISSUE TITLE
make multiav-build failed

### ISSUE THREAD

**Issue by najashark** [saferwall/saferwall#241]
I tried to build multiav images using `make multiav-build` mention in docs but it seems docker doesn't understand the -t/--tag argument that passed to it.

systems:
- OS : `Ubuntu 18.04.5`
- Docker : `Docker version 19.03.13, build 4484c46d9d`
- Minikube : `minikube version: v1.12.2 commit: be7c19d391302656d27f1f213657d925c4e1cfc2-dirty`
- Kubectl:
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- go : `go version go1.15.2 linux/amd64`

Error msg:
```bash
user@saferwall:~/saferwall$ make multiav-build
for av in /home/user/saferwall/pkg/grpc/multiav ; do \
	echo " [*] =============== Building $av =============== " ; \
	make multiav-build-av AV_VENDOR=$av ; \
	EXIT_CODE=$? ; \
	if test $EXIT_CODE ! 0; then \
		make multiav-build-av AV_VENDOR=$av ; \
	fi; \
done
 [*] =============== Building /home/user/saferwall/pkg/grpc/multiav =============== 
make[1]: Entering directory '/home/user/saferwall'
invalid argument "saferwall//home/user/saferwall/pkg/grpc/multiav" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
build/mk/docker.mk:4: recipe for target 'docker-build' failed
make: *** [docker-build] Error 125
build/mk/multiav.mk:20: recipe for target 'multiav-build-av' failed
make[1]: *** [multiav-build-av] Error 2
make[1]: Leaving directory '/home/user/saferwall'
/bin/bash: line 4: test: !: binary operator expected
```
The argument that passed to -t/--tag parameter was `saferwall//home/user/saferwall/pkg/grpc/multiav` should it be something like this`saferwall/multiav` ?

**Comment by LordNoteworthy** [comment]
I see the problem.

I just fixed it ! Thanks. 

Can you pull the branch `master` and retry again please ?

**Comment by najashark** [comment]
Thanks! it works now, can let me know whats is the username and password to login? i have tried credentials from here but its not working
https://github.com/saferwall/saferwall/blob/master/deployments/saferwall/files/consumer-conf.toml
