### ISSUE TITLE
AVs not actually working

### ISSUE THREAD

**Issue by tldale** [saferwall/saferwall#258]
When scanning files they get all the green pass boxes but in reality they are not even being scanned:

{"level":"error","msg":"Failed to scan file [avira]: rpc error: code = Unknown desc = signal: killed","sha256":"36384e03d05303377c152e81fe7adf20aaeb5f453ec5433498da2e74f9088478","time":"2020-12-15T18:17:43Z"}
{"level":"error","msg":"Failed to scan file [comodo]: rpc error: code = Unknown desc = signal: killed","sha256":"36384e03d05303377c152e81fe7adf20aaeb5f453ec5433498da2e74f9088478","time":"2020-12-15T18:17:46Z"}

root@saferwall1:~# kubectl logs venus-saferwall-multiav-avira-855d75fcff-tk9kp
time="2020-12-15T17:35:59Z" level=info msg="Starting Avira gRPC server ..."
root@saferwall1:~# kubectl logs venus-saferwall-multiav-comodo-fd5fcb85f-kvqv2
time="2020-12-15T17:36:06Z" level=info msg="Starting Comodo gRPC server ..."

**Comment by LordNoteworthy** [comment]
Hello @tldale 

I will try to solve your issues one by one.

So which setup did you use to get this output ? (kind, minikube or vagrant ? ) ?

**Comment by tldale** [comment]
The only way i was able to get this even remotely online on a system system was using the dev instructions of building it line by line. Your Vagrant file doesn't work as it has the wrong ssh key with it and will not authenticate. Everything is running BUT clamav as it keeps saying its dying because of OOM even though i'm running a system with 32GB of ram and its only using about 7G with this setup.

**Comment by tldale** [comment]
Hello @LordNoteworthy,

I was able to get 3 out of the 4 to work by building the AVs manually. WinDefender is the only one still giving me issues. 

When i get the log from the consumer container:

root@saferwall1:/opt/saferwall# kubectl logs venus-saferwall-consumer-5667cdd9d-ql7jc
time="2020-12-16T16:11:33Z" level=info msg="Config saferwall.prod was loaded"
{"level":"error","msg":"exiftool pkg failed with: exit status 1","sha256":"275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f","time":"2020-12-16T16:27:48Z"}
{"level":"error","msg":"Failed to scan file [windefender]: rpc error: code = Unknown desc = signal: illegal instruction (core dumped)","sha256":"275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f","time":"2020-12-16T16:27:48Z"}
{"level":"error","msg":"Failed to scan file [windefender]: rpc error: code = Unknown desc = signal: illegal instruction (core dumped)","sha256":"2546dcffc5ad854d4ddc64fbf056871cd5a00f2471cb7a5bfd4ac23b6e9eedad","time":"2020-12-16T16:29:25Z"}
root@saferwall1:/opt/saferwall#
When i get the log from windefender contrainer:

root@saferwall1:/opt/saferwall# kubectl logs venus-saferwall-multiav-windefender-7c9666f5bf-b9qx8
time="2020-12-16T16:09:37Z" level=info msg="Starting Windows Defender gRPC server ..."
root@saferwall1:/opt/saferwall#

Also i noticed that even if the multiav isnt running it says "Clean" you should return a value of "Not Running" or something of the sort with maybe a yellow explanation or question mark. This way people are less confused when running files through. Also your website to test saferwall.com is down. "saferwall.com’s server IP address could not be found."

Thanks,

**Comment by tldale** [comment]
Another update! It seems running the following command 'make multiav-build-go' returned this at the end:

All done, no errors.
Removing intermediate container 9f5d074e943f
 ---> 84e5b15b428e
Step 16/21 : RUN cd $WINDOWS_DEFENDER_INSTALL_DIR     && ./mpclient /eicar 2>&1 | grep -q 'Virus:DOS/EICAR_Test_File'
 ---> Running in 0a9aca211e1f
Illegal instruction (core dumped)
The command '/bin/sh -c cd $WINDOWS_DEFENDER_INSTALL_DIR     && ./mpclient /eicar 2>&1 | grep -q 'Virus:DOS/EICAR_Test_File'' returned a non-zero code: 1
make: *** [build/mk/docker.mk:4: docker-build] Error 1
make[1]: *** [build/mk/multiav.mk:79: multiav-build-av-go] Error 2
make[1]: Leaving directory '/opt/saferwall'
/bin/bash: line 4: test: !: binary operator expected
root@saferwall1:/opt/saferwall#

**Comment by tldale** [comment]
A helm repo broke now.

root@saferwall1:/opt/saferwall# make helm-release
cd /opt/saferwall/deployments \
        && helm install -name venus \
         --namespace default saferwall
Error: found in Chart.yaml, but missing in charts/ directory: minio, efs-provisioner, nfs-server-provisioner
make: *** [build/mk/helm.mk:28: helm-release] Error 1
root@saferwall1:/opt/saferwall#

**Comment by tldale** [comment]
@LordNoteworthy,

Further update after updating the repo now this happens:

Error: template: saferwall/charts/deprecation/templates/NOTES.txt:10:3: executing "saferwall/charts/deprecation/templates/NOTES.txt" at <fail "\n*******************************************************\n* This chart location is deprecated. Learn more here: *\n* https://helm.sh/blog/charts-repo-deprecation/       *\n*******************************************************\n">: error calling fail:
*******************************************************
* This chart location is deprecated. Learn more here: *
* https://helm.sh/blog/charts-repo-deprecation/       *
*******************************************************

make: *** [build/mk/helm.mk:28: helm-release] Error 1


You can no longer bring this up at all.

Thank you!

**Comment by LordNoteworthy** [comment]
Hey @tldale , can you join [Gitter ](https://gitter.im/saferwall/community) chat please ? let me help you with setup.

Cheers.

**Comment by tldale** [comment]
Hey buddy have you been on Gitter lately? Tried to follow up with you after the holidays but haven't had any return messages from ya.

Thanks a bunch!

**Comment by LordNoteworthy** [comment]
I will close this issue as it solves your initial problem.

We will push a doc page to helm building paid AV softwares,
