### ISSUE TITLE
DeadlineExceeded in gRPC services

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#302]
Getting a timeout in gRPC servers:

```Failed to scan file [X]: rpc error: code = DeadlineExceeded desc = context deadline exceeded```

**Comment by LordNoteworthy** [comment]
@actuallyachraf so far one issue that I can tell, for large files, it does timeout, I increased the timeout and I am monitoring it now.

**Comment by LordNoteworthy** [comment]
For files that are ~30 MB, it is a bit much to keep the string extractor extract strings with 5 chars, it produces a lot of garbage strings.

**Comment by actuallyachraf** [comment]
@LordNoteworthy I am thinking we can up the limit to 8 and drop strings with length < 8
We could use `gib` to filter gibberish strings but we'll need to see about the FP rate it produces (I am working on an alternative algorithm just need to collect enough data for it).
