### ISSUE TITLE
loki scanner

### ISSUE THREAD

**Issue by MariasStory** [saferwall/saferwall#336]
Hi, please include the loki scanner:
https://github.com/Neo23x0/Loki
https://hub.docker.com/r/mablanco/loki

**Comment by SteveBox0** [comment]
Agreed, would be handy.

**Comment by LordNoteworthy** [comment]
Good to hear someone else want this feature, I will see when I can include it.

**Comment by LordNoteworthy** [comment]
Update: We will add our own Yara scanning and IOC.

Yara will be used to scan original sample and memory dumps.
IOC will be extracted from the sandbox output.

Stay tunned, this will be released soon.
