### ISSUE TITLE
im sorry, i cant found  github.com/saferwall/multiav project

### ISSUE THREAD

**Issue by mel2oo** [saferwall/saferwall#343]
go: github.com/saferwall/multiav@v0.1.6: reading github.com/saferwall/multiav/go.mod at revision v0.1.6: unknown revision v0.1.6

**Comment by LordNoteworthy** [comment]
Hello @switch-li 

I am aware of this, it happens because that module is private. I am not sure how to fix this one really. Gimme some time and I will get back to you.

Btw for what reason you need the `saferwall` go mod ?

**Comment by LordNoteworthy** [comment]
Hello @mel2oo 

I have fixed the issue. Now you can do a go get without issues.
