### ISSUE TITLE
jupiter-saferwall-webApis Error - CrashLoopBackOff 

### ISSUE THREAD

**Issue by 0xjustBen** [saferwall/saferwall#365]
Hello Saferwall team,

Thank you for this really nice project. 

I'm trying to make it run locally on a Ubuntu 18.04.6 VM. 
I'm using the documentation DEPLOYING-DEV.md and deploying it using kind. I didn't change anything on the value.yaml file, the installation went okay but,
it seems that the container for the api doesn't work properly and it never runs. The issue for the container went from CrashLoopBackOff to Error. 

![image](https://user-images.githubusercontent.com/77623466/149125998-0970803b-fb07-4cc2-80c2-035d1bac9a10.png)

Regarding the event you'd have an idea watching this screenshoot:
![image](https://user-images.githubusercontent.com/77623466/149126446-fe9af28b-3aea-455d-9da3-a4fb365f88ac.png)

Did you ever get this issue and is there a mitigation?

Thanks in advance,

**Comment by Hakdat** [comment]
I am also facing the same issue.. I tried to solve it but I failed every time. Please review on it.

**Comment by 0xjustBen** [comment]
I'm working on the fix, it should be done in few days.

**Comment by MinhKMA** [comment]
I am also facing the same issue. Did you fix this bug?

**Comment by LordNoteworthy** [comment]
I fixed that one, once I merge the PR, that should be fixed.

**Comment by MinhKMA** [comment]
Could you sent me the PR to i will follow it?

**Comment by LordNoteworthy** [comment]
Can you please have a look again ?

You would need to delete the cluster, pull the last changes and create the cluster again.

One more thing is you probably wanna run this command before you start:

```
helm repo remove minio
```

And also make sure to  grab the new kind with `make kind-install`. Feel free to join discord if you get stuck.
