### ISSUE TITLE
Antivirus engine and definitions update

### ISSUE THREAD

**Issue by analyserdmz** [saferwall/saferwall#370]
GREAT project!

How do we update the engine and the definitions all together for each antivirus?

**Comment by LordNoteworthy** [comment]
Hey @analyserdmz 

Are you building your own docker images or are you using the public ones ?

**Comment by analyserdmz** [comment]
@LordNoteworthy atm I am experimenting with the public ones. The final purpose is to have an isolated multiple antivirus solution that would communicate only with certain intranet endpoints but this is too far for now.

For now the only thing that matters is the on-demand antivirus update :)

**Comment by LordNoteworthy** [comment]
Hello @analyserdmz 

I added a github action that will run every day to update the signatures:
![image](https://user-images.githubusercontent.com/5129564/163195961-c9a6b808-017d-4b2d-a428-406a18ac2297.png)

You can simply run this command which will reload the images and eventually pull the new containers that have the new av signatures updates:

```
kubectl get deployment | grep multiav | awk '{print $1}' | kubectl rollout restart deployment
```
