### ISSUE TITLE
Dont found image saferwall/ml-pipeline:latest

### ISSUE THREAD

**Issue by MinhKMA** [saferwall/saferwall#371]
Looks like this image is not public
```
ERROR: pull access denied for saferwall/ml-pipeline, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by LordNoteworthy** [comment]
Hello @MinhKMA 

Normally, that project is private. Thats why the docker img is not public.

I discussed it with the guy who is working on the ML side of saferwall, he will open source it soon.

**Comment by MinhKMA** [comment]
so, Can I deploy saferwall by docker-compose file?

**Comment by LordNoteworthy** [comment]
I set the image to public, you can pull the docker image now.

The source code will be public some time soon.

I use docker-compose only for local debugging, I will do some more tests and I will write some docs about it when I have time.
