### ISSUE TITLE
McAfee doesn't report other kind of malware besides trojan

### ISSUE THREAD

**Issue by prsyahmi** [saferwall/saferwall#385]
Hi, this was due to regex used here: https://github.com/saferwall/saferwall/blob/main/internal/multiav/mcafee/mcafee.go#L101

Changing `Found the (.*) trojan` to `Found the (.*) \w+ !!!` will fix the problem
```
	// /home/ubuntu/malware ... Found the RDN/Generic.tfr trojan !!!
	// /home/ubuntu/malware ... Found the W32/Rontokbro.a.gen@MM virus !!!

	// Time: 00:00.00

	// Grab the detection result
	re := regexp.MustCompile(`Found the (.*) \w+ !!!`)
```

This will cover everything including if the malware name contain spaces

Also, I had to removed the return code check and rely solely on regex because it doesn't return results.
```
	//if err != nil && err.Error() != "exit status 13" {
	//	return res, err
	//}
```

**Comment by LordNoteworthy** [comment]
Hey @prsyahmi 

That's a good catch ! I probably know why you needed to omit the code check, exit code 13 means a trojan detection, so if there is something like PUA detection, it will have its own exit code?, I will double check that.

**Comment by LordNoteworthy** [comment]
I decide to have a look at other detections that might break the regex:

- Found potentially unwanted program Dialer-RAS.az. <-- still missing this if you enable PUA detection
- Found the W32/Ramnit.a!htm virus !!! <-- thanks to your help, we can now see this one.
- Found trojan or variant JS/HideLink.A !!! <--  still missing this if you enable heuristic scan

I will update the code so we can catch all those cases, thanks !

**Comment by LordNoteworthy** [comment]
I just pushed a PR to fix this. This should normally catch them all now, I only tests a 100 of samples, I need to do a more aggressive scan later to find out what can break that regex.

For now, can please tell me what was the exit code that made you comment out this:

```go
	//if err != nil && err.Error() != "exit status 13" {
	//	return res, err
	//}
```

**Comment by prsyahmi** [comment]
I just retry it and indeed it is returning `13`, probably it was due to timeout.

**Comment by LordNoteworthy** [comment]
The new container should have the fix, let me know if it works for you.

If the timeout makes it hard to test, I will create a PR for the timeout issue.

**Comment by prsyahmi** [comment]
Hi @LordNoteworthy ,

I just tried the latest commit and it returns `the` 😄 

![image](https://user-images.githubusercontent.com/1040494/200638708-372b16a2-ff38-4520-b4d4-03ead8415cc0.png)

Using non-capturing group `(?:xxx)` should works, at least in my case:
```Found (?:the|potentially unwanted program|trojan or variant) (.*) (?:!!!|\.)```

**Comment by LordNoteworthy** [comment]
Just fetch the last image, it should work.

**Comment by LordNoteworthy** [comment]
Can you please check now.

**Comment by prsyahmi** [comment]
It is working now, thanks!
