### ISSUE TITLE
[core] identify suspicious strings

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#39]
- build an ML classifier to classify a string as suspicious.
- expose a service via our back end api so users can find out potentially suspicious strings.

**Comment by evalsocket** [comment]
I want to work on that. Do you have any dataset for training.

**Comment by LordNoteworthy** [comment]
Hey @evalsocket, that's amazing! I appreciate your motivation.

I have a terabyte of samples on my hard disk. I guess I need to:

- First, upload them so they can be scanned.
- Second, we need to filter out the junk samples or the duplicated ones so we can extract only the relevant ones you can use in training. As there is currently no way to cluster them, we will rely blindly on AV detection names.
- Then I will run some queries over the DB and get you few samples per malware family.

In the end, as an output, you would get a JSON or a CSV with the following schema:
ZBot | hash1,hash2,hash3, ....
Gamarue | hash1,hash2,hash3, ....

I will do the same for clean files.

Once this is done. You can either use the strings pkg available in this repo to extract the strings.

Would that be OK? What do you think?

I will need a week to generate the data.

Cheers.

**Comment by evalsocket** [comment]
@LordNoteworthy that would be a great

**Comment by LordNoteworthy** [comment]
Hello @evalsocket,

I just finished the triage. I am currently uploading it. Sorry for 3 extra days delay.

**Comment by LordNoteworthy** [comment]
@evalsocket I am creating a set of clear programs as well, gimme some time as I am trying to be super careful about the collection.

**Comment by evalsocket** [comment]
@LordNoteworthy what is the password for zip file ?

**Comment by LordNoteworthy** [comment]
infected

**Comment by actuallyachraf** [comment]
What's the current integration plan for this issue ?

**Comment by actuallyachraf** [comment]
> infected

Let's make this as default password for sharing samples and share it on a separate github repo
