### ISSUE TITLE
XSS in the Comment Page

### ISSUE THREAD

**Issue by huvuqu** [saferwall/saferwall#394]
Store XSS in the Comment Page.
You should do HTML encode all user input when return this data in HTTP response.

![xss1](https://user-images.githubusercontent.com/22325354/207561382-495c7ca8-b25f-4e02-9fda-b182236c7585.png)
![xss2](https://user-images.githubusercontent.com/22325354/207561397-a3540815-2ec8-48cc-beff-7c6dbbc38e93.png)

**Comment by LordNoteworthy** [comment]
Hello @huvuqu 

Thanks a lot for reporting, @yassinrais can you please have a look.

**Comment by LordNoteworthy** [comment]
Deployed the new version.
