### ISSUE TITLE
Not found repository saferwall/goavast & saferwall/goeset

### ISSUE THREAD

**Issue by johnsaker97** [saferwall/saferwall#396]
Hi team, 
I'm building project using k8s. I tried using extend AV: avast & goeset but have error: **Pod errors: ImagePullBackOff**

I have checked image on https://hub.docker.com/u/saferwall, it also not found 2 images above.

Please support for me!

**Comment by LordNoteworthy** [comment]
Hello @johnsaker97 

The reason is because those AVs requires a license, that's why I have them private in dockerhub.

If you want to use them, you need to purchase a license and build the containers yourself.

Cheers.
