### ISSUE TITLE
Alert user to sign in when attempting to upload file without being logged in

### ISSUE THREAD

**Issue by SteveBox0** [saferwall/saferwall#399]
Looks like saferwall.com stopped processing or uploading files 8 days ago.

**Comment by LordNoteworthy** [comment]
Hmm, I just scanned a new file, what error this you received in the website ?

![image](https://user-images.githubusercontent.com/5129564/210343963-aa2d5f88-af2a-496b-aded-ce67aceeb94e.png)

**Comment by SteveBox0** [comment]
Apologies, it seems the upload page is available when not login but only uploads correctly when signed in. Might be worth having a message saying you must be login to upload.

**Comment by LordNoteworthy** [comment]
@yassinrais check this.

**Comment by yassinrais** [comment]
Okey 👌🏻, i will fix it

**Comment by LordNoteworthy** [comment]
@yassinrais is this fixed in current UI ?

**Comment by yassinrais** [comment]
Yes
<img width="965" alt="image" src="https://user-images.githubusercontent.com/25354731/216210598-ce29be4f-b84b-4bf8-bbe5-7af5f2eab0b8.png">
