### ISSUE TITLE
saferwall/sandbox docker image not found

### ISSUE THREAD

**Issue by Siam-1998** [saferwall/saferwall#449]
I am installing saferwall on the ubuntu server but, the installation is not successfully done and an error showing

ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling sandbox (saferwall/sandbox:latest)...
ERROR: pull access denied for saferwall/sandbox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

How to solve this problem?

**Comment by LordNoteworthy** [comment]
Hello @Siam-1998, as you can see in the `values.yaml`, the sandbox is not atm available for public "community" version and it might never be.

We're still develping it aiming for it to be released at end of year.

You will be able to use the hosted version in https://saferwall.com and APIs will also be available.
