### ISSUE TITLE
failed to run the server: unambiguous timeout

### ISSUE THREAD

**Issue by deheshjou** [saferwall/saferwall#461]
hello
after running the command "make dc-up SVC="sandbox"" it says:
failed to run the server: unambiguous timeout | {\"InnerError\":.........

all containers are running perfectly and I have ran it based on the tutorials provided
can you tell me how to resolve the error
thanks in advance

**Comment by LordNoteworthy** [comment]
Hello @deheshjou 

The sandbox is not released yet, and most likely won't be available for a self-hosted option.

It will be available to use soon on the cloud version hosted on https://saferwall.com.

Cheers.
