### ISSUE TITLE
Missing AV base container images

### ISSUE THREAD

**Issue by sm-rii** [saferwall/saferwall#469]
It looks like all of the base container images are unavailable and the Dockerfile's don't exist? Example output:

failed to solve: failed to read dockerfile: open Dockerfile.trendmicro: no such file or directory

All of the go enabled Dockerfiles use a FROM of those base images but if they are unavailable how could we build? Thanks for the info.

**Comment by LordNoteworthy** [comment]
I am so sorry @sm-rii  for the super delayed response.

As I mentioned in the doc, they need to be built as I can't include the ones that requires license.  I will update the documentation some time here, you can follow this issue: https://github.com/saferwall/saferwall/issues/282
