### ISSUE TITLE
[ui] update packages to last stable

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#47]
This task is about getting familir with the UI code base, and update packages to last stable.

**Comment by mrassili** [comment]
There are still a few plugins that depend on some old packages, will update them as we go through

**Comment by LordNoteworthy** [comment]
Makes perfect sense, thanks a lot.

One more thing, the README inside UI folder, if needs to be updated to reflect the new changes, you can update it as well, so I always know how to start it correctly.

**Comment by mrassili** [comment]
Of course, working on it
