### ISSUE TITLE
[ui] Fix broken AntiVirus View

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#56]
Hey @mrassili 

The **Antivirus** view needs some tweaks to get it work again. It is currently broken due to the json response from the server, which have been slightly changed.

Before, the json was like this
```
{
    "av": {
        "first_scan": [
            {
                "detected": true,
                "output": "Win32:Ransom-AQL [Trj]",
                "vendor": "Avast"
            },
            {
                "detected": true,
                "output": "TR/Crilock.A.11",
                "vendor": "Avira"
            },
        ],
        "last_scan": [
            {
                "detected": true,
                "output": "Win32:Ransom-AQL [Trj]",
                "vendor": "Avast"
            },
            {
                "detected": true,
                "output": "TR/Crilock.A.11",
                "vendor": "Avira"
            },
            {
                "detected": false,
                "output": "Clean",
                "vendor": "ClamAV"
            },
            {
                "detected": true,
                "output": "Win32/Filecoder.BQ",
                "vendor": "ESET-NOD32"
            },
   
        ]
    },
```
The string **output** becomes **result**. The **vendor** now becomes outside the dict.

After:

```
 "multiav": {
    "first_scan": {
      "Avast": {
        "detected": false,
        "result": ""
      },
      "Bitdefender": {
        "detected": true,
        "result": "Not-a-virus:HEUR:AdWare.Win32.Generic"
      },
      "Microsoft": {
        "detected": true,
        "result": "PUA:Win32/Puwaders.B!ml"
      },
      "clamav": {
        "detected": true,
        "result": "Win32:DealPly-AJ [Adw]"
      }
    },
    "last_scan": {
      "Avast": {
        "detected": false,
        "result": ""
      },
      "Bitdefender": {
        "detected": true,
        "result": "Not-a-virus:HEUR:AdWare.Win32.Generic"
      },
      "Microsoft": {
        "detected": true,
        "result": "PUA:Win32/Puwaders.B!ml"
      },
      "clamav": {
        "detected": true,
        "result": "Win32:DealPly-AJ [Adw]"
      }
    }
  },
```

The number if dicts inside this array is not fixable, you should be able to iterate through it
The result at the end should look like this:

<p align="center"> 
    <img src="https://i.imgur.com/RKmnR4j.png" width="auto" height="auto">
</p>

**Comment by mrassili** [comment]
Just a remark, is the new JSON format forced or did you choose to make it like that ? Because the way it is now is not optimal for storing data (data is best stored in array as in the old JSON, than in object props)

**Comment by LordNoteworthy** [comment]
Good remark. I made it that way.

The advantage I can see is that you can get the result of an vendor without the need to iterate through the whole list. When users will consumers our APIs directly to get the scan results, their might be looking to know the result on a particular vendor. Although, iterating over that list is not really time consuming, it is a list which could go for a max of 60.

**Comment by mrassili** [comment]
I see, let's keep it that way, and change in the future as needed :)
