### ISSUE TITLE
[ui] Design a sign in/sign up page

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#97]
Hello @mrassili 

We need to design a sign in / sign up page.

Sign up contains the following input fields

- email
- username
- password

Plus a checkbox about: I agree to the [terms and conditions](url)
Then a button to Submit.

Notes:
- We dont need a repeat password. 
- Fot the moment, let's enforce any 8 char length.
- Input should be highlighted by red/green depending on success. I will give you later how you can contact the backend to know if username/email are available. In this task, you can just check if email format is valid in client side.

Sign in contains the following fields
- email or username
- password

Not a member ? [Sign up](url)
Forgot [password ](url)?

Below is an example, the form should be placed in the center of the page, under our logo, also only the header (top navbar) and the footer should exist in the page, no left sidebar.

<p align="center"> 
    <img src="https://i.imgur.com/VrQwtQ4.png" width="auto" height="auto">
</p>

Logo: https://github.com/saferwall/saferwall/blob/master/website/_assets/images/saferwall.png

You can check the dashboard I provided before, at the section forms, there are examples you can use.

Cheers,

**Comment by mrassili** [comment]
Just to be sure, the login in question is different than the one on saferwall.com. right?
I am not sure what dashboard you're referring to, care to specify?

**Comment by mrassili** [comment]
Can you specify which main pages should be available for guests and which one are for authenticated users. Also if there is any page exclusive for admins, please say so.
I can help if you let me know what feature should be available for guests and I'll figure out the rest

**Comment by LordNoteworthy** [comment]
Yes, it is different from the one in saferwal.com, that on should be removed.

All the issues title which starts with [ui] related to the dashboard only.

Atm, we have /upload which should requried auth.

Otherwise, everything else is public.

**Comment by LordNoteworthy** [comment]
@mrassili 

Additing to what mentionned before:
- Let's include a show password icon.
- For username, we should apply some more validation, a regex one like `[a-z0-9_-.]{3,20}$` but if you want to do it properly, check this [thread](https://stackoverflow.com/questions/1221985/how-to-validate-a-user-name-with-regex ) as we dont want also usernames to have only underscrores or hyphens.

1. To register a new account, send a **POST** request to `api.saferwall.com/auth/register`:
- it expects a username, password, and email, in success, it returns an HTTP status code 201.
- if email/username exists or invalid data passed like wrong email format, it returns HTTP status code 400 with a json in body which gives you more details about the error, the key in json is "*verbose_msg*".
- upon failure, we should alert the user with a notification.
- upon success, we should redirect to the login view and notify that email address needs to be verified.

2. To login, you need to issue a GET request to `api.saferwall.com/auth/login`

- it expects a username, password sent as a POST request.
- we should apply same validations we did for user registration for username and password.
- upon successful login, you will get a cookie which contains a jwt token, we use a cookie to store a token instead of localstorage for security reasons.

I did not implement my part in the backend yet, but prepares you to do something in client side.

**Comment by LordNoteworthy** [comment]
Code is deployed now, you can test it in the endpoint as we discussed in slack.
