### ISSUE TITLE
[ui] file upload

### ISSUE THREAD

**Issue by LordNoteworthy** [saferwall/saferwall#98]
Hey @mrassili 

Till now, we have not been uploading files to the backend, we only used data which already was available on the database. The upload part is one of the most important ones, it needs to be reliable. You are free to use whatever library you want or you can roll your own, but it should support the following features:

- Drag & drop support
- Upload progress bar
- Chunked uploads (Large files can be uploaded in smaller chunks with browsers supporting the Blob API).

When the file gets selected in the browser, we calculate :
1. Its size first, if more than 64MB, we should notify the user the file size is too big (this is already implemented), but I would like to change the notification style to the one available in vue-admin under : `/components/notification`

2. If size is OK, we locally calculate its sha256 hash (this is already implemented), then, we issue a  **GET** to `api.saferwall.com/v1/files/<sha256>`, if file exists (status code 200), we redirect to the summary view of the hash.  Because the file exists, we do not need to upload it, we just fetch the JSON immediately and display as before, this way we don't waste bandwidth.

3. If the file does not exist, you need to make a **POST** request to the following endpoint: `api.saferwall.com/v1/files`, it is a multipart form upload, if the server returns status code 201, it means all went fine and we need to display a progress tracker similar to the one in vue-admin under: `/components/progress-tracker`:

- Step 1: Uploaded
- Step 2: Queued
- Step 3: Processing
- Step 4: Finished

When the file gets successfully uploaded, you can keep pulling the server by making a **GET** request to `api.saferwall.com/v1/files/<sha256>`, the JSON will contain a state variable to indicate the progress of the scan, called **status**. We might user socket io later to avoid this pulling.

<p align="center"> 
    <img src="https://i.imgur.com/n6VDV9w.png" width="auto" height="auto">
</p>

Thanks!

**Comment by LordNoteworthy** [comment]
The backend side is set now for this to be working, have fun :)

**Comment by LordNoteworthy** [comment]
Gonna be ready tomorrow.

**Comment by LordNoteworthy** [comment]
The file upload is working now, I am just trying to finalize something so you can get the status field updated. So today you can still work on uploading the files, it should work and you should get a 201 status code, but the status field wont be updated.

**Comment by mrassili** [comment]
Noted. Will start working on those in the morning

**Comment by mrassili** [comment]
Hey @LordNoteworthy 
The summary section in the left menu, should be disabled by default, am I right?
After user selects a file only then we redirect to summary?

**Comment by LordNoteworthy** [comment]
**1. The summary section in the left menu, should be disabled by default, am I right?**
Yes, it should be disabled if the user is trying to upload a file. It should be actually enabled only if the user is looking at the content of a file scan result.
**2. After user selects a file only then we redirect to the summary?**
So when the user logs in, we should point him to the upload view,  once he selects a file, we calculate its sha256, and we issue a get request to grab the scan result of that file:
- if the file exists, you will get a JSON which contains everything you need, you will redirect the user to `http://saferwall.com/#/summary/sha256`
- if the file does not exist, it will be uploaded, and you're gonna keep polling the server until you got a result then you redirect to  `http://saferwall.com/#/summary/<sha256>`,  while pulling, it would be better for the user to see some progress, that's what I described before. It is something like this:
https://nigelotoole.github.io/progress-tracker/, and have those steps:
Step 1: Uploaded
Step 2: Queued
Step 3: Processing
Step 4: Finished

**Comment by mrassili** [comment]
Couldn't use `https://github.com/vue-bulma/progress-tracker`
It depends on an older version of `Bulma`
But I'll try to find a maintained one or come up with something similar
